### ISSUE TITLE
NoSuchMethodError: 'void org.bukkit.command.SimpleCommandMap.<init>(org.bukkit.Server, java.util.Map)'

### ISSUE THREAD

**Issue by Chafficui** [MockBukkit/MockBukkit#1022]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version of MockBukkit?

- [X] I am using the latest version of MockBukkit.

### Minecraft Version

1.20

### Describe the bug

It seems like there is an error with the SimpleCommandMap in the latest version (3.89.0). This error appears whenever I am using MockBukkit.mock.
```NoSuchMethodError: 'void org.bukkit.command.SimpleCommandMap.<init>(org.bukkit.Server, java.util.Map)'```

It does not happen in version 3.88.1

### Reproducible Test

Get mockbukkit through maven:
```
        <dependency>
            <groupId>com.github.seeseemelk</groupId>
            <artifactId>MockBukkit-v1.20</artifactId>
            <version>3.89.0</version>
            <scope>test</scope>
        </dependency>
```

Write a setUp method
```
    @BeforeEach
    public void setUp() {
        server = MockBukkit.mock();
    }
```

And run a test

**Comment by Insprill** [comment]
What Paper version are you building against?

**Comment by Chafficui** [comment]
I've tried it with spigot 1.20.3-R0.1 and 1.20.6-R0.1

**Comment by Thorinwasher** [comment]
> I've tried it with spigot 1.20.3-R0.1 and 1.20.6-R0.1

You need to use paper 1.20.6

**Comment by Insprill** [comment]
Yup, only Paper 1.20.6 is supported. If you need to build on Spigot 1.20.6, put MockBukkit above Spigot in your `pom.xml`.

**Comment by Chafficui** [comment]
@Insprill Hey, thanks for the quick solution to my problem!
One question: Is this documented somewhere? I wasn't able to find it in the README. Maybe I am just blind.

**Comment by mechoriet** [comment]
I'm getting this same error/exception

even tried your example event https://mockbukkit.readthedocs.io/en/latest/events.html#asserting-that-events-were-fired 
but below error was also shown since my code was just to see it if worked and expand on that

To my knowledge I did the right steps?

pom.xml:
```xml
<dependency>
    <groupId>com.github.seeseemelk</groupId>
    <artifactId>MockBukkit-v1.20</artifactId>
    <version>3.93.2</version>
    <scope>test</scope>
</dependency>
<dependency>
    <groupId>io.papermc.paper</groupId>
    <artifactId>paper-api</artifactId>
    <version>1.20.6-R0.1-SNAPSHOT</version>
    <scope>test</scope>
</dependency>
```

class:
```java
public class TestCommand
{
    private ServerMock server;
    private testPlugin plugin;

    @BeforeEach
    public void setUp() {
        // Start the mock server
        server = MockBukkit.mock();
        // Load your plugin
        plugin = MockBukkit.load(testPlugin.class);
    }

    @AfterEach
    public void tearDown() {
        // Stop the mock server
        MockBukkit.unmock();
    }

    @Test
    public void testPlayeradd() {
        PlayerMock player = server.addPlayer();
    }

}
```
error/exception:
```bash
java.lang.NoSuchMethodError: 'void org.bukkit.command.SimpleCommandMap.<init>(org.bukkit.Server, java.util.Map)'

	at be.seeseemelk.mockbukkit.command.MockCommandMap.<init>(MockCommandMap.java:25)
	at be.seeseemelk.mockbukkit.ServerMock.<init>(ServerMock.java:192)
	at be.seeseemelk.mockbukkit.MockBukkit.mock(MockBukkit.java:61)
	at dev.ednoy.helpers.common.command.TestCommand.setUp(TestCommand.java:18)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
```
